services:
  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=miniprojet
      - MONGO_INITDB_ROOT_PASSWORD=miniprojet2025
  
  mongo-express:
    image: mongo-express:latest
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: miniprojet
      ME_CONFIG_MONGODB_ADMINPASSWORD: miniprojet2025
      ME_CONFIG_MONGODB_URL: mongodb://miniprojet:miniprojet2025@mongodb:27017/miniprojet?authSource=admin
      ME_CONFIG_BASICAUTH: false

volumes:
  mongodb_data: